{{- $fullName    := include "postgres.fullname" . -}}
{{- $secretName  := default $fullName .Values.secretName -}}
{{- if .Values.config -}}
---
apiVersion:                       v1
kind:                             Secret
metadata:
  name:                           {{ $secretName }}
  labels:
{{ include "postgres.labels" . | indent 4 }}
type:                             Opaque
data:
{{- range $name, $value := .Values.secrets }}
{{- if not (empty $value) }}
  {{ $name }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
{{- end }}
