{{- $fullName    := include "postgres.fullname" . -}}
{{- $secretName  := default $fullName .Values.secretName -}}
{{- $configName  := default $fullName .Values.configName -}}
---
apiVersion:                      apps/v1
kind:                            StatefulSet
metadata:
  name:                          {{ $fullName }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  serviceName:                   {{ $fullName }}
  replicas:                      1
  selector:
    matchLabels:
      {{- include "postgres.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "postgres.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name:                  postgres
          image:                 {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy:       {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name:            {{ $configName }}
          ports:
            - containerPort:     {{ .Values.service.port }}
              name:              postgres
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name:              pgdata
              mountPath:         /var/lib/postgresql
            - name:              pg-pass
              mountPath:         /secrets
              readOnly:          true
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready
                - --dbname=$POSTGRES_DB
                - --username=$POSTGRES_USER
            initialDelaySeconds: 15
            timeoutSeconds:      5
            failureThreshold:    3
            periodSeconds:       10
            successThreshold:    1
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready
                - --dbname=$POSTGRES_DB
                - --username=$POSTGRES_USER
            initialDelaySeconds: 30
            timeoutSeconds:      5
            failureThreshold:    3
            periodSeconds:       10
            successThreshold:    1
      volumes:
        - name:                  pg-pass
          secret:
            secretName:          {{ $secretName }}
        - name:                  pgdata
          persistentVolumeClaim:
            claimName:           pgdata
  volumeClaimTemplates:
    - metadata:
        name:                    pgdata
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName:        {{ .Values.storage.className }}
        resources:
          requests:
            storage:             {{ .Values.storage.size }}
