nameOverride:             ""
fullnameOverride:         ""
config:
  POSTGRES_DB:            postgres
  POSTGRES_USER:          postgres
  POSTGRES_PASSWORD_FILE: /secrets/POSTGRES_PASSWORD
secrets:
  POSTGRES_PASSWORD:      wengo4eed3Eebein6O
image:
  repository:             postgres
  pullPolicy:             IfNotPresent
  tag:                    ""
service:
  type:                   ClusterIP
  port:                   5432
storage:
  className:              fast
  size:                   10Gi
resources:
  requests:
    cpu:                  150m
    memory:               256Mi
  limits:
    cpu:                  500m
    memory:               1Gi
